(Concept history-intelligence-tools-language
  (V-predicate
    (Property
      (intelligence (WorldSpecSet ()) 1.0)
      (tools (WorldSpecSet ()) 1.0)
      (language (WorldSpecSet ()) 1.0))))

(Concept history-intelligence-tools-strategy
  (V-predicate
    (Property
      (intelligence (WorldSpecSet ()) 1.0)
      (tools (WorldSpecSet ()) 1.0)
      (strategy (WorldSpecSet ()) 1.0))))

(Concept history-intelligence-tools-engineering
  (V-predicate
    (Property
      (intelligence (WorldSpecSet ()) 1.0)
      (tools (WorldSpecSet ()) 1.0)
      (engineering (WorldSpecSet ()) 1.0))))

(Concept history-intelligence-tools-logic
  (V-predicate
    (Property
      (intelligence (WorldSpecSet ()) 1.0)
      (tools (WorldSpecSet ()) 1.0)
      (logic (WorldSpecSet ()) 1.0))))

(Concept history-climbing-agility-balance
  (V-predicate
    (Property
      (climbing (WorldSpecSet ()) 1.0)
      (agility (WorldSpecSet ()) 1.0)
      (balance (WorldSpecSet ()) 1.0))))

(Concept history-climbing-agility-vertical
  (V-predicate
    (Property
      (climbing (WorldSpecSet ()) 1.0)
      (agility (WorldSpecSet ()) 1.0)
      (vertical (WorldSpecSet ()) 1.0))))

(Concept history-climbing-agility-ropes
  (V-predicate
    (Property
      (climbing (WorldSpecSet ()) 1.0)
      (agility (WorldSpecSet ()) 1.0)
      (ropes (WorldSpecSet ()) 1.0))))

(Concept history-webs-insects-sticky
  (V-predicate
    (Property
      (webs (WorldSpecSet ()) 1.0)
      (insects (WorldSpecSet ()) 1.0)
      (sticky (WorldSpecSet ()) 1.0))))
