"""Quantale adaptations of the Fauconnier-Turner OP constraints."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field

from a_quantale_theoretic_approach.core_representation.product_quantale import ProductQuantale
from a_quantale_theoretic_approach.core_representation.v_predicate import VPredicateConcept
from a_quantale_theoretic_approach.optimality.constraint_types import (
    CrossMapping,
    QuantaleConditionResult,
    QuantaleRelation,
    RelationSet,
)
from a_quantale_theoretic_approach.optimality.quantale_helpers import (
    combined_universe,
    hom_value,
    join_values,
    property_support,
    rebase_concept,
    score_value,
    source_support_for_blend_property,
    unit,
)
from a_quantale_theoretic_approach.optimality.semantic_oracle import SemanticOracle
from a_quantale_theoretic_approach.structural_reasoning.quantale_colimit_engine import QuantaleColimitResult


@dataclass
class QuantaleOptimalityContext:
    """Inputs shared by all quantale OP condition adapters."""

    source_a: VPredicateConcept
    source_b: VPredicateConcept
    colimit: QuantaleColimitResult
    candidate_blend: VPredicateConcept | None = None
    canonical_colimit: QuantaleColimitResult | None = None
    relations: RelationSet = field(default_factory=RelationSet)
    relevance: Mapping[str, ProductQuantale | float] | None = None
    oracle: SemanticOracle = field(default_factory=SemanticOracle)
    semantic_threshold: float = 0.65

    @property
    def blend(self) -> VPredicateConcept:
        return self.candidate_blend or self.colimit.blend

    @property
    def canonical_blend(self) -> VPredicateConcept:
        return (self.canonical_colimit or self.colimit).blend

    @property
    def universe(self) -> tuple[str, ...]:
        return combined_universe(self.source_a, self.source_b, self.blend, self.canonical_blend)

    @property
    def property_maps(self) -> dict[str, dict[str, str]]:
        return self.colimit.property_maps


class QuantaleConstraint:
    name = "constraint"
    threshold = 0.5

    def condition(self, value: ProductQuantale, details: dict, *, skipped: bool = False) -> QuantaleConditionResult:
        return QuantaleConditionResult(
            name=self.name,
            value=value,
            tv_score=value.tv.value,
            passed=skipped or value.tv.value >= self.threshold,
            skipped=skipped,
            details=details,
        )

    def evaluate(self, context: QuantaleOptimalityContext) -> QuantaleConditionResult:
        raise NotImplementedError


class IntegrationCondition(QuantaleConstraint):
    """Integration as equality/support against the canonical V-predicate colimit."""

    name = "integration"
    threshold = 0.7

    def evaluate(self, context: QuantaleOptimalityContext) -> QuantaleConditionResult:
        universe = context.universe
        canonical = rebase_concept(context.canonical_blend, universe)
        candidate = rebase_concept(context.blend, universe)
        canonical_to_candidate = hom_value(
            canonical,
            candidate,
            universe=universe,
            oracle=context.oracle,
            semantic_threshold=context.semantic_threshold,
        )
        candidate_to_canonical = hom_value(
            candidate,
            canonical,
            universe=universe,
            oracle=context.oracle,
            semantic_threshold=context.semantic_threshold,
        )
        value = canonical_to_candidate * candidate_to_canonical
        return self.condition(
            value,
            {
                "canonical_to_candidate": canonical_to_candidate.to_metta(),
                "candidate_to_canonical": candidate_to_canonical.to_metta(),
                "canonical_property_count": len(canonical.entries),
                "candidate_property_count": len(candidate.entries),
            },
        )


class GoodReasonCondition(QuantaleConstraint):
    """Good Reason: every blend property is generated by input support."""

    name = "good_reason"
    threshold = 0.7

    def evaluate(self, context: QuantaleOptimalityContext) -> QuantaleConditionResult:
        universe = context.universe
        blend = rebase_concept(context.blend, universe)
        source_a = rebase_concept(context.source_a, universe)
        source_b = rebase_concept(context.source_b, universe)
        aggregate = unit(universe)
        unsupported: list[str] = []
        property_scores: dict[str, float] = {}

        for prop_name, entry in blend.entries.items():
            support = source_support_for_blend_property(
                prop_name,
                source_a,
                source_b,
                context.colimit.contributions,
                universe=universe,
                oracle=context.oracle,
                semantic_threshold=context.semantic_threshold,
            )
            if support.tv.value == 0.0 and context.oracle.is_property_justified(prop_name, blend.name):
                support = score_value(0.7, universe)
            prop_value = entry.quantale.with_universe(universe) >> support
            aggregate = aggregate * prop_value
            property_scores[prop_name] = round(prop_value.tv.value, 6)
            if prop_value.tv.value < self.threshold:
                unsupported.append(prop_name)

        return self.condition(
            aggregate,
            {
                "property_scores": property_scores,
                "unsupported_properties": unsupported,
                "uses_colimit_contributions": True,
            },
        )


class UnpackingCondition(QuantaleConstraint):
    """Unpacking as recoverability from source contributions and semantic support."""

    name = "unpacking"
    threshold = 0.65

    def evaluate(self, context: QuantaleOptimalityContext) -> QuantaleConditionResult:
        universe = context.universe
        blend = rebase_concept(context.blend, universe)
        source_a = rebase_concept(context.source_a, universe)
        source_b = rebase_concept(context.source_b, universe)

        aggregate = unit(universe)
        property_scores: dict[str, float] = {}
        for prop_name, entry in blend.entries.items():
            support = source_support_for_blend_property(
                prop_name,
                source_a,
                source_b,
                context.colimit.contributions,
                universe=universe,
                oracle=context.oracle,
                semantic_threshold=context.semantic_threshold,
            )
            prop_value = entry.quantale.with_universe(universe) >> support
            aggregate = aggregate * prop_value
            property_scores[prop_name] = round(prop_value.tv.value, 6)

        hom_a_c = hom_value(
            source_a,
            blend,
            universe=universe,
            property_map=context.property_maps.get("A", {}),
            oracle=context.oracle,
            semantic_threshold=context.semantic_threshold,
        )
        hom_b_c = hom_value(
            source_b,
            blend,
            universe=universe,
            property_map=context.property_maps.get("B", {}),
            oracle=context.oracle,
            semantic_threshold=context.semantic_threshold,
        )
        hom_c_a = hom_value(blend, source_a, universe=universe, oracle=context.oracle)
        hom_c_b = hom_value(blend, source_b, universe=universe, oracle=context.oracle)
        split_approximation = (hom_c_a * hom_a_c) + (hom_c_b * hom_b_c)

        return self.condition(
            aggregate,
            {
                "property_scores": property_scores,
                "split_approximation": split_approximation.to_metta(),
                "hom_a_c": hom_a_c.to_metta(),
                "hom_b_c": hom_b_c.to_metta(),
                "hom_c_a": hom_c_a.to_metta(),
                "hom_c_b": hom_c_b.to_metta(),
            },
        )


class RelevanceCondition(QuantaleConstraint):
    """Relevance as weighted/filtered V-predicate weakness."""

    name = "relevance"
    threshold = 0.5

    def evaluate(self, context: QuantaleOptimalityContext) -> QuantaleConditionResult:
        universe = context.universe
        if not context.relevance:
            return self.condition(unit(universe), {"reason": "no relevance valuation provided"}, skipped=True)

        blend = rebase_concept(context.blend, universe)
        values: list[ProductQuantale] = []
        used: dict[str, str] = {}
        for prop_name, entry in blend.entries.items():
            raw_weight = context.relevance.get(prop_name)
            if raw_weight is None:
                continue
            if isinstance(raw_weight, ProductQuantale):
                weight = raw_weight.with_universe(universe)
            else:
                weight = score_value(float(raw_weight), universe)
            values.append(weight * entry.quantale.with_universe(universe))
            used[prop_name] = weight.to_metta()

        if not values:
            return self.condition(score_value(0.0, universe), {"reason": "no blend properties passed relevance filter"})
        value = join_values(values, universe)
        return self.condition(value, {"used_relevance_weights": used})


def _relation_value(
    relation: QuantaleRelation,
    concept: VPredicateConcept,
    universe: tuple[str, ...],
    oracle: SemanticOracle,
) -> ProductQuantale:
    if relation.value is not None:
        return relation.value.with_universe(universe)
    source_support = property_support(
        relation.source_property,
        concept,
        universe=universe,
        explicit_target_property=relation.source_property,
        oracle=oracle,
    )
    target_support = property_support(
        relation.target_property,
        concept,
        universe=universe,
        explicit_target_property=relation.target_property,
        oracle=oracle,
    )
    return source_support * target_support


def _mapped_relation(
    relation: QuantaleRelation,
    property_map: Mapping[str, str],
) -> tuple[str, str]:
    return (
        property_map.get(relation.source_property, relation.source_property),
        property_map.get(relation.target_property, relation.target_property),
    )


def _best_blend_relation_support(
    relation_type: str,
    source_property: str,
    target_property: str,
    blend_relations: list[QuantaleRelation],
    blend: VPredicateConcept,
    universe: tuple[str, ...],
    oracle: SemanticOracle,
    semantic_threshold: float,
) -> ProductQuantale:
    candidates: list[ProductQuantale] = []
    for blend_relation in blend_relations:
        type_similarity = oracle.similarity(relation_type, blend_relation.relation_type)
        source_similarity = oracle.similarity(source_property, blend_relation.source_property)
        target_similarity = oracle.similarity(target_property, blend_relation.target_property)
        similarity = min(type_similarity, source_similarity, target_similarity)
        if similarity < semantic_threshold:
            continue
        bridge = score_value(similarity, universe)
        candidates.append(_relation_value(blend_relation, blend, universe, oracle) * bridge)
    return join_values(candidates, universe) if candidates else score_value(0.0, universe)


class TopologyCondition(QuantaleConstraint):
    """Topology/Web preservation for source vital relations."""

    name = "topology"
    threshold = 0.6

    def evaluate(self, context: QuantaleOptimalityContext) -> QuantaleConditionResult:
        universe = context.universe
        if not context.relations.source_a and not context.relations.source_b:
            return self.condition(unit(universe), {"reason": "no source relation data provided"}, skipped=True)

        blend = rebase_concept(context.blend, universe)
        source_a = rebase_concept(context.source_a, universe)
        source_b = rebase_concept(context.source_b, universe)
        aggregate = unit(universe)
        checked = []

        for source_label, source, relations, prop_map in (
            ("A", source_a, context.relations.source_a, context.property_maps.get("A", {})),
            ("B", source_b, context.relations.source_b, context.property_maps.get("B", {})),
        ):
            for relation in relations:
                mapped_source, mapped_target = _mapped_relation(relation, prop_map)
                expected = _relation_value(relation, source, universe, context.oracle)
                support = _best_blend_relation_support(
                    relation.relation_type,
                    mapped_source,
                    mapped_target,
                    context.relations.blend,
                    blend,
                    universe,
                    context.oracle,
                    context.semantic_threshold,
                )
                preservation = expected >> support
                aggregate = aggregate * preservation
                checked.append(
                    {
                        "source": source_label,
                        "relation": relation.relation_type,
                        "mapped": [mapped_source, mapped_target],
                        "score": round(preservation.tv.value, 6),
                    }
                )

        return self.condition(aggregate, {"checked_relations": checked})


class WebCondition(QuantaleConstraint):
    """Old Web-OP adaptation: cross mappings are maintained in blend relations."""

    name = "web"
    threshold = 0.6

    def evaluate(self, context: QuantaleOptimalityContext) -> QuantaleConditionResult:
        universe = context.universe
        if not context.relations.cross_mappings:
            return self.condition(unit(universe), {"reason": "no cross mappings provided"}, skipped=True)

        blend = rebase_concept(context.blend, universe)
        source_a = rebase_concept(context.source_a, universe)
        source_b = rebase_concept(context.source_b, universe)
        aggregate = unit(universe)
        checked = []

        for mapping in context.relations.cross_mappings:
            mapped_a = _mapped_relation(mapping.concept_a_relation, context.property_maps.get("A", {}))
            mapped_b = _mapped_relation(mapping.concept_b_relation, context.property_maps.get("B", {}))
            expected_a = _relation_value(mapping.concept_a_relation, source_a, universe, context.oracle)
            expected_b = _relation_value(mapping.concept_b_relation, source_b, universe, context.oracle)
            expected = expected_a * expected_b * score_value(mapping.confidence, universe)
            support_a = _best_blend_relation_support(
                mapping.concept_a_relation.relation_type,
                mapped_a[0],
                mapped_a[1],
                context.relations.blend,
                blend,
                universe,
                context.oracle,
                context.semantic_threshold,
            )
            support_b = _best_blend_relation_support(
                mapping.concept_b_relation.relation_type,
                mapped_b[0],
                mapped_b[1],
                context.relations.blend,
                blend,
                universe,
                context.oracle,
                context.semantic_threshold,
            )
            support = support_a + support_b
            score = expected >> support
            aggregate = aggregate * score
            checked.append({"mapped_a": mapped_a, "mapped_b": mapped_b, "score": round(score.tv.value, 6)})

        return self.condition(aggregate, {"checked_cross_mappings": checked})


class MetonymicTighteningCondition(QuantaleConstraint):
    """Metonymic tightening adapted from old compressed-relation checks."""

    name = "metonymic_tightening"
    threshold = 0.5

    def evaluate(self, context: QuantaleOptimalityContext) -> QuantaleConditionResult:
        universe = context.universe
        if not context.relations.blend and not context.relations.cross_mappings:
            return self.condition(unit(universe), {"reason": "no blend relation data provided"}, skipped=True)

        if context.relations.cross_mappings:
            return self._evaluate_cross_mapping_tightening(context)

        blend = rebase_concept(context.blend, universe)
        compressed_values = []
        checked = []
        for relation in context.relations.blend:
            compressed = (
                context.oracle.is_compressed_relation(relation.relation_type)
                or context.oracle.is_metonymy(relation.relation_type, relation.target_property)
                or context.oracle.is_part_of(relation.target_property, blend.name)
            )
            relation_q = _relation_value(relation, blend, universe, context.oracle)
            checked.append(
                {
                    "relation": relation.relation_type,
                    "compressed": compressed,
                    "score": round(relation_q.tv.value if compressed else 0.0, 6),
                }
            )
            if compressed:
                compressed_values.append(relation_q)

        if not context.relations.blend:
            value = unit(universe)
        else:
            ratio = len(compressed_values) / len(context.relations.blend)
            value = score_value(ratio, universe)
        return self.condition(value, {"checked_relations": checked})

    def _evaluate_cross_mapping_tightening(
        self,
        context: QuantaleOptimalityContext,
    ) -> QuantaleConditionResult:
        universe = context.universe
        blend = rebase_concept(context.blend, universe)
        source_a = rebase_concept(context.source_a, universe)
        source_b = rebase_concept(context.source_b, universe)
        aggregate = unit(universe)
        checked = []

        for mapping in context.relations.cross_mappings:
            mapped_a = _mapped_relation(mapping.concept_a_relation, context.property_maps.get("A", {}))
            mapped_b = _mapped_relation(mapping.concept_b_relation, context.property_maps.get("B", {}))
            expected = (
                _relation_value(mapping.concept_a_relation, source_a, universe, context.oracle)
                * _relation_value(mapping.concept_b_relation, source_b, universe, context.oracle)
                * score_value(mapping.confidence, universe)
            )
            support_a = _best_blend_relation_support(
                mapping.concept_a_relation.relation_type,
                mapped_a[0],
                mapped_b[1],
                context.relations.blend,
                blend,
                universe,
                context.oracle,
                context.semantic_threshold,
            )
            support_b = _best_blend_relation_support(
                mapping.concept_b_relation.relation_type,
                mapped_a[0],
                mapped_b[1],
                context.relations.blend,
                blend,
                universe,
                context.oracle,
                context.semantic_threshold,
            )
            support = support_a + support_b
            score = expected >> support
            aggregate = aggregate * score
            checked.append({"mapped_source": mapped_a[0], "mapped_target": mapped_b[1], "score": round(score.tv.value, 6)})

        return self.condition(aggregate, {"checked_tightenings": checked})
