name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.6'

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip==23.1.2
        python -m pip install -r requirements.txt


    - name: Run Tests
      run: |
        cd ../conceptBlending
        python scripts/run-tests.py
